#!/bin/sh
# vim: set ft=sh

set -ex

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

source=$1

if [ -z "$source" ]; then
  echo "usage: $0 <path/to/source>"
  exit 1
fi

# for jq
PATH=/usr/local/bin:$PATH

payload=$(mktemp $TMPDIR/git-resource-request.XXXXXX)

cat > $payload <&0

load_pubkey $payload

uri=$(jq -r '.source.uri // ""' < $payload)
repo=$(jq -r '.source.repo// ""' < $payload)
username=$(jq -r '.source.username // ""' < $payload)
access_token=$(jq -r '.source.access_token // ""' < $payload)
repository=$(jq -r '.params.repository // ""' < $payload)
state=$(jq -r '.params.state // "failure"' < $payload)
description=$(jq -r '.params.description // ""' < $payload)


cd $source
cd $repository

ref=$(git rev-parse HEAD)

curl -u $username:$access_token --data "{ \"state\" : \"$state\", \"description\" : \"$description\" }" https://api.github.com/repos/$username/$repo/statuses/$ref

jq -n "{
  version: {ref: $(echo $ref | jq -R .)}
}" >&3
